config/routes.rb
Uplodar::Engine.routes.draw do

  resources :events, :only => [:index, :show]
  resources :shares do
    resources :users, :controller => 'assignments', :only => :index
  end
  resources :users, :only => :index do
    resources :shares, :controller => 'assignments', :only => [:index, :show, :update] do
      collection do
        get :assignments
        put :assign
      end
    end
  end

  match '/browser/'                           => 'browser#create', :as => :browser_create, :via => :post
  match '/browser/edit/:share(/*path)/:entry' => 'browser#edit',   :as => :browser_edit,   :via => :get,    :constraints => {:entry => /.*/}
  match '/browser/update'                     => 'browser#update', :as => :browser_update, :via => :post
  match '/browser/:share(/*path)/:entry'      => 'browser#delete', :as => :browser_delete, :via => :delete, :constraints => {:entry => /.*/}
  match '/browser/:share(/*path)'             => 'browser#index',  :as => :browser,        :via => :get

  root :to => 'home#index'
end

app/models/uplodar/event.rb
module Uplodar
  class Event < ActiveRecord::Base
    paginates_per 5

    belongs_to :user, :class_name => Uplodar.user_class.to_s
    belongs_to :share

    attr_accessible :msg, :action, :share_id, :user_id

    before_validation :cached_fields

    private

    def cached_fields
      self.username = self.user.send Uplodar.display_user_name
      self.sharename = self.share.name
    end
  end
end

app/models/uplodar/fs_manager.rb
require 'mime/types'
require 'pathname'
require 'open-uri'

module Uplodar
  class FsManager
    attr_reader :share, :path,
      :current_path, :current_url, :current_lpath, 
      :breadcrumps, :dirs, :files

    VALID_CHARACTERS = "a-zA-Z0-9~!@$%^&*()#`_+-=<>\"{}|[];',?".freeze

    def initialize(share, path = nil)
      @share, @path = share, path
      setup
    end

    def setup
      make_currents
      make_breadcrumbs
      make_list
    end

    def entries
      @dirs.concat(files)
    end

    def make_file_obj(file)
      pname = Pathname.new(file)
      ptype = pname.ftype

      return nil unless ['directory', 'file'].include? ptype

      { :name => pname.basename, :type => ptype, :size => pname.size }
    end


    def self.make_dir(path, dir)
      new_dir = File.join(path, dir)

      return nil if !self.valid_path?(new_dir)
      return nil if File.exists? new_dir

      Dir.mkdir(new_dir)
    end

    def self.save_file(path, file)
      return nil unless File.exists? path

      tmp      = File.join(path, file.original_filename)
      new_file = tmp
      cntr     = 1

      while File.exists? new_file
        new_file = "#{tmp}.#{cntr}"
        cntr += 1
      end

      return nil if !self.valid_path?(new_file)

      File.open(new_file, "wb") {|f| f.write( file.read ) }
    end

    def self.move(old, new)
      return false if !File.exist? old
      return false if File.exist? new

      return nil if !self.valid_path?(old)
      return nil if !self.valid_path?(new)

      FileUtils.mv(old, new)
    end

    def self.delete(path, entry)
      tmp = File.join(path, entry)

      return nil if !self.valid_path?(tmp)

      FileUtils.rm_rf(tmp) if File.exists? tmp
    end

    private

    def make_currents
      if @path.blank?
        @current_path  = @share.path
        @current_url   = @share.url
        @current_lpath = @share.name
      else
        @current_path  = File.join(@share.path, @path)
        @current_url   = File.join(@share.url, @path)
        @current_lpath = File.join(@share.name, @path)
      end

      @current_url = URI::encode(@current_url)
    end

    def make_breadcrumbs
      @breadcrumps = @current_lpath.split('/')
    end

    def make_list
      @dirs = []
      @files = []

      Dir.glob("#{@current_path}/*").sort.each do |file|
        file_obj = make_file_obj(file)
        next if file_obj.blank?

        case file_obj[:type]
        when  'directory' then @dirs  << file_obj
        when  'file'      then @files << file_obj
        end

      end
    end

    def detect_mime(file)
      tmp = MIME::Types.type_for(file)
      return "unknown" if tmp.empty?

      case tmp.first.content_type
      when "video/x-msvideo", "video/quicktime", "video/vnd.objectvideo", "application/mp4"
        "video"
      when "audio/mpeg", "audio/x-wav"
        "audio"
      when "image/png", "image/jpeg"
        "image"
      when  "application/x-bzip2",  "application/x-gzip", 
        "application/zip",      "application/x-rar-compressed",
        "application/x-gtar"
        "archive"
      when "application/pdf"
        "pdf"
      when "application/octet-stream"
        "binary"
      else
        tmp.first.content_type
      end
    end

    def self.valid_path?(path)
      path == Pathname.new(path.tr("^#{VALID_CHARACTERS}", '')).cleanpath.to_s
    end

  end
end

app/models/uplodar/share.rb
module Uplodar
  class Share < ActiveRecord::Base
    has_many  :share_assignments
    has_many  :users, :through => :share_assignments, :class_name => Uplodar.user_class.to_s

    attr_accessible :name, :path, :url

    validates :name, :presence => true, :uniqueness => true
    validates :path, :presence => true, :uniqueness => true
    validates :url,  :presence => true, :uniqueness => true

  end
end

app/models/uplodar/share_assignment.rb
module Uplodar
  class ShareAssignment < ActiveRecord::Base
    attr_accessible :user_id, :share_id, :write

    belongs_to :user
    belongs_to :share

    after_save    :save_cached_shares
    after_destroy :save_cached_shares

    private
    def save_cached_shares
      user = self.user
      user.cached_shares = user.shares.map{|r| r.name.downcase}.join(', ')
      user.save
    end
  end
end

app/controllers/uplodar/application_controller.rb
require 'cancan'

module Uplodar
  class ApplicationController < ActionController::Base



    def current_ability
       @current_ability ||= UplodarAbility.new(current_user)
    end

    rescue_from CanCan::AccessDenied do |e|
      redirect_to root_url, :alert => e.message
    end

    rescue_from ActiveRecord::RecordNotFound do |e|
      redirect_to root_url, :alert => "Page not found"
    end
  end
end

app/controllers/uplodar/assignments_controller.rb
require_dependency "uplodar/application_controller"

module Uplodar
  class AssignmentsController < ApplicationController
    before_filter :authenticate_user!
    before_filter :get_user

    def index
      if !@user.blank?
        @shares = @user.share_assignments.select('uplodar_shares.id, uplodar_share_assignments.write, uplodar_shares.name').joins(:share)
      elsif !@share.blank?
        @users  = @share.share_assignments.select('users.id, uplodar_share_assignments.write, users.email').joins(:user)
      end
    end

    def show
      @share      = @user.shares.find(params[:id])
      @assignment = @user.share_assignments.where(:share_id => params[:id]).first
    end

    def update
      @assignment = @user.share_assignments.find(params[:id])

      respond_to do |f|
        if @assignment.update_attributes(params[:share_assignment])
          f.html { redirect_to user_shares_url(@user), :notice => 'Share assignment was successfully updated.' }
        else
          f.html { render :action => "show" }
        end
      end
    end

    def assignments
    end

    def assign
      respond_to do |f|
        if @user.update_attributes(params[:user])
          f.html { redirect_to user_shares_url(@user), :notice =>  'User was successfully updated.' }
        else
          f.html { render :action => "assignments" }
        end
      end
    end

    private
    def get_user
      @user  = Uplodar.user_class.find(params[:user_id])  unless params[:user_id].blank?
      @share = Share.find(params[:share_id])              unless params[:share_id].blank?
    end

  end
end

app/controllers/uplodar/browser_controller.rb
require_dependency "uplodar/application_controller"

module Uplodar
  class BrowserController < ApplicationController
    before_filter :authenticate_user!

    def index
      setup(params[:share], params[:path])
      authorize! :read, @share
    end

    def create
      setup(params[:browser][:share], params[:browser][:path])
      authorize! :write, @share

      if !params[:browser][:new_file].blank?
        FsManager.save_file(@fsm.current_path, params[:browser][:new_file])
        write_event("Upload", "#{File.join(@fsm.current_path, params[:browser][:new_file].original_filename)}")

      elsif !params[:browser][:new_dir].blank?
        FsManager.make_dir(@fsm.current_path, params[:browser][:new_dir])
        write_event("Create", "#{File.join(@fsm.current_path, params[:browser][:new_dir])}")

      else
        redirect_to root_url && return
      end
    end

    def edit
      setup(params[:share], params[:path])
      authorize! :write, @share
      @entry  = params[:entry]
    end

    def update
      setup(params[:browser][:share], params[:browser][:path])
      authorize! :write, @share

      @path      = @fsm.current_path
      @new_path  = params[:browser][:new_path].blank? ? @path : File.join(@fsm.current_path, params[:browser][:new_path])

      #TODO: this has to be reviewd
      @entry     = params[:browser][:entry]
      @new_entry = params[:browser][:new_entry].blank? ? @entry : params[:browser][:new_entry]

      FsManager.move(File.join(@path, @entry), File.join(@new_path, @new_entry))
      write_event("Move", "#{File.join(@path, @entry)} --> #{File.join(@new_path, @new_entry)}")
    end


    def delete
      setup(params[:share], params[:path])
      authorize! :write, @share

      FsManager.delete(@fsm.current_path, params[:entry])
      write_event("Delete", "#{File.join(@fsm.current_path, params[:entry])}")
    end

    private

    def setup(share, path)
      @share  = (current_user.is_uplodar_admin? ? Share : current_user.shares).where(:name => share).first
      @fsm    = FsManager.new(@share, path)
      rel_url = relative_url_root
      mnt_url = Rails.application.routes.named_routes[:uplodar].path
      mnt_url =  mnt_url.spec.to_s if mnt_url.respond_to?(:spec)
      @suburi = rel_url.blank? ? mnt_url.to_s : File.join(rel_url, mnt_url).to_s
    end

    def write_event(action, msg)
      Event.create(:share_id => @share.id, :user_id => current_user.id, :action => action, :msg => msg)
    end

  end
end

app/controllers/uplodar/events_controller.rb
require_dependency "uplodar/application_controller"

module Uplodar
  class EventsController < ApplicationController
    load_and_authorize_resource

    def index
      @events = Event.order("created_at DESC").page(params[:page])
      respond_to do |f|
        f.html  {render 'index'}
        f.js    {render 'index'}
      end
    end

    def show
    end
  end
end

app/controllers/uplodar/home_controller.rb
require_dependency "uplodar/application_controller"

module Uplodar
  class HomeController < ApplicationController
    before_filter :authenticate_user!

    def index
      @shares = current_user.is_uplodar_admin? ? Share.all : current_user.shares
      #redirect_to browser_url(:share => @shares.first.name) if @shares.length == 1
    end

    private
    def check_or_login
      redirect_to main_app.new_user_session_url unless current_user
    end
  end
end

app/controllers/uplodar/share_assignments_controller.rb
require_dependency "uplodar/application_controller"

module Uplodar
  class ShareAssignmentsController < ApplicationController
    before_filter :get_user

    def index
      @shares = @user.share_assignments.select('uplodar_shares.id, uplodar_share_assignments.write, uplodar_shares.name').joins(:share)
    end

    def show
      @share      = @user.shares.find(params[:id])
      @assignment = @user.share_assignments.where(:share_id => params[:id]).first
    end

    def update
      @assignment = @user.share_assignments.find(params[:id])

      respond_to do |f|
        if @assignment.update_attributes(params[:share_assignment])
          f.html { redirect_to user_shares_url(@user), :notice => 'Share assignment was successfully updated.' }
        else
          f.html { render :action => "show" }
        end
      end
    end

    def assignments
    end

    def assign
      respond_to do |f|
        if @user.update_attributes(params[:user])
          f.html { redirect_to user_shares_url(@user), :notice =>  'User was successfully updated.' }
        else
          f.html { render :action => "assignments" }
        end
      end
    end

    private
    def get_user
      @user = Uplodar.user_class.find(params[:user_id])
    end

  end
end

app/controllers/uplodar/shares_controller.rb
require_dependency "uplodar/application_controller"

module Uplodar
  class SharesController < ApplicationController
    load_and_authorize_resource

    def index
    end

    def show
    end

    def new
    end
    def edit
    end

    def create
      respond_to do |format|
        if @share.save
          format.html { redirect_to @share, :notice => 'Share was successfully created.' }
        else
          format.html { render :action => "new" }
        end
      end
    end

    def update
      respond_to do |format|
        if @share.update_attributes(params[:share])
          format.html { redirect_to @share, :notice =>  'Share was successfully updated.' }
        else
          format.html { render :action => "edit" }
        end
      end
    end

    def destroy
      @share.destroy

      respond_to do |format|
        format.html { redirect_to shares_url }
      end
    end
  end
end

app/controllers/uplodar/users_controller.rb
require_dependency "uplodar/application_controller"

module Uplodar
  class UsersController < ApplicationController
    before_filter :authenticate_user!

    def index
      @users = Uplodar.user_class.all
    end
  end
end

app/helpers/uplodar/application_helper.rb
module Uplodar
  module ApplicationHelper

    def title(page_title, show_title = true)
      @show_title = show_title
      @content_for_title = page_title.to_s
    end

    def show_title?
      @show_title
    end

    def stylesheet(*args)
      content_for(:head) { stylesheet_link_tag(*args) }
    end

    def javascript(*args)
      content_for(:head) { javascript_include_tag(*args) }
    end

    def entry_icon(entry_type)
      case entry_type
      when 'directory'
        "icon-folder-open"
      else
        "icon-file"
      end
    end
  end
end

app/helpers/uplodar/share_assignments_helper.rb
module Uplodar
  module ShareAssignmentsHelper
  end
end

app/views/uplodar/assignments/_form.html.erb
<div class="row">
<%= simple_form_for(@assignment, :url => user_shares_path(@user), :html => { :class => 'form-horizontal'}) do |f| %>

  <div class="span6">
    <dl class="dl-horizontal">
      <dt><strong><%= Uplodar.display_user_name %></strong></dt>
      <dd><%= @user.send Uplodar.display_user_name %></dd>
    </dl>
  </div>

  <div class="span6">
    <legend>Shares</legend>
    <%= f.association :shares, :as => :check_boxes, :label => false %>
  </div>

  <div class="span12">
    <div class="form-actions">
      <%= f.submit 'Update user\' s permissions', :class => 'btn btn-primary' %>
      <div class="pull-right">
        <%= link_to 'Cancel', user_shares_path(@user), :class => 'btn' %>
      </div>
    </div>
  </div>

<% end %>
</div>

app/views/uplodar/assignments/_shares.html.erb
<div class="page-header">
  <h2>Users for <%= @share.name %></h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>can write?</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
    <td><%= user.send Uplodar.display_user_name %></td>
    <td><%= user.id %></td>
    <td>
      <span class="pull-right">
        <%= link_to 'Details', user_share_path(user, @share), :class => 'btn btn-primary btn-mini' %>
      </span>
    </td>
  </tr>
<% end %>
  </tbody>
</table>
<%#= link_to "Assign Share", assignments_user_shares_path(user), :class => 'btn btn-primary' %>

app/views/uplodar/assignments/_users.html.erb
<div class="page-header">
  <h2>Shares for <%= @user.send Uplodar.display_user_name %></h2>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Shares</th>
      <th>can write?</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @shares.each do |share| %>
    <tr>
    <td><%= share.name %></td>
    <td><%= share.write %></td>
    <td>
      <span class="pull-right">
        <%= link_to 'Details', user_share_path(@user, share), :class => 'btn btn-primary btn-mini' %>
      </span>
    </td>
  </tr>
<% end %>
  </tbody>
</table>
<%= link_to "Assign Share", assignments_user_shares_path(@user), :class => 'btn btn-primary' %>

app/views/uplodar/assignments/assignments.html.erb
<div class="page-header">
  <h1>Assign share</h1>
</div>

<div class="row">
<%= simple_form_for(@user, :url => assign_user_shares_path(@user), :html => { :class => 'form-horizontal'}) do |f| %>

  <div class="span6">
    <dl class="dl-horizontal">
      <dt><strong><%= Uplodar.display_user_name %></strong></dt>
      <dd><%= @user.send Uplodar.display_user_name %></dd>
    </dl>
  </div>

  <div class="span6">
    <legend>Shares</legend>
    <%= f.association :shares, :as => :check_boxes, :label => false %>
  </div>

  <div class="span12">
    <div class="form-actions">
      <%= f.submit 'Update user\' s shares', :class => 'btn btn-primary' %>
      <div class="pull-right">
        <%= link_to 'Cancel', user_shares_path(@user), :class => 'btn' %>
      </div>
    </div>
  </div>

<% end %>
</div>

app/views/uplodar/assignments/edit.html.erb
<div class="page-header">
  <h1>Add share</h1>
</div>
<%= render 'form' %>

app/views/uplodar/assignments/index.html.erb
<% if !@user.blank? %>
  <%= render 'users' %>
<% elsif !@share.blank? %>
  <%= render 'shares' %>
<% end %>

app/views/uplodar/assignments/show.html.erb
<div class="page-header">
  <h2>Permissions for <%= @user.send Uplodar.display_user_name %> on "<%= @share.name %>"</h2>
</div>

<div class="row">
<%= simple_form_for(@assignment, :url => user_share_path(@user, @assignment), :html => { :class => 'form-horizontal'}) do |f| %>

  <div class="span12">
    <legend>Permissions:</legend>
    <%= f.input :write %>
  </div>

  <div class="span12">
    <div class="form-actions">
      <%= f.submit 'Update user\' s permissions', :class => 'btn btn-primary' %>
      <div class="pull-right">
        <%= link_to 'Cancel', user_shares_path(@user), :class => 'btn' %>
      </div>
    </div>
  </div>

<% end %>
</div>